stock.out: *.cpp ../abstract_stock/*.cpp ../abstract_stock/*.h ../../UI/text_file_handler.cpp ../../UI/text_file_handler.h
	g++ -std=c++11 -o stock.out ../abstract_stock/*.cpp *.cpp ../../UI/text_file_handler.cpp
