central.out: *.cpp ../lib/network/*.cpp ../lib/network/*.h *.h ../lib/abstract_stock/*.cpp ../lib/abstract_stock/*.h
	g++ -std=c++11 -pthread -o central.out *.cpp ../lib/network/*.cpp ../lib/abstract_stock/*.cpp
