UI.out: main.cpp ../lib/client_socket.cpp ../lib/network_socket.cpp command_handler.cpp ../lib/interthreadcom.cpp
	g++ -std=c++11 -pthread -o UI.out main.cpp ../lib/client_socket.cpp ../lib/network_socket.cpp command_handler.cpp ../lib/interthreadcom.cpp
